import { Router } from 'express';
import { PrismaClient } from '@prisma/client';
import puppeteer from 'puppeteer';

const router = Router();
const prisma = new PrismaClient();

// GET daily report aggregations for the web UI
router.get('/daily', async (req, res) => {
  try {
    const audits = await prisma.materialAudit.findMany({
      include: { items: true },
      orderBy: { date: 'desc' },
      take: 30
    });

    const delays = await prisma.delay.findMany({
      orderBy: { date: 'desc' },
      take: 30
    });

    const attendances = await prisma.attendance.findMany({
      include: { crew: true },
      orderBy: { date: 'desc' },
      take: 30
    });

    res.json({ audits, delays, attendances });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// GET export PDF
router.get('/export-pdf', async (req, res) => {
  try {
    const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
            h1 { color: #0284c7; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
            .section { margin-top: 30px; }
            .metric { font-size: 24px; font-weight: bold; color: #16a34a; }
            table { width: 100%; border-collapse: collapse; margin-top: 15px; }
            th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; }
            th { background-color: #f8fafc; font-weight: bold; }
          </style>
        </head>
        <body>
          <h1>BuildWise - Project Executive Report</h1>
          <p>Date: ${new Date().toLocaleDateString('en-GB')}</p>
          
          <div class="section">
            <h2>Project Status</h2>
            <p>Overall Health: <span class="metric">ON TRACK</span></p>
          </div>

          <div class="section">
            <h2>Recent Delays</h2>
            <table>
              <tr><th>Date</th><th>Cause</th><th>Severity</th></tr>
              <tr><td>Yesterday</td><td>Weather</td><td>Low</td></tr>
              <tr><td>2 Days Ago</td><td>Material</td><td>Medium</td></tr>
            </table>
          </div>
          
          <div style="margin-top: 50px; font-size: 12px; color: #94a3b8; text-align: center;">
            Auto-generated by BuildWise Intelligence
          </div>
        </body>
      </html>
    `;

    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
    await page.setContent(htmlContent);
    
    const pdfBuffer = await page.pdf({ format: 'A4', printBackground: true });
    
    await browser.close();

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=project-report.pdf');
    res.send(Buffer.from(pdfBuffer));
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
